name: Build and Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies, build, and deploy
      run: |
        npm install --global yarn
        yarn
        yarn build
      env:
        CI: true
#    - name: GitHub Pages Deploy
#      uses: maxheld83/ghpages@v0.2.1
#      with:
#        secrets: "GITHUB_TOKEN"
#      env:
#        BUILD_DIR: "build/"
        
    - name: Deploy site to gh-pages branch
      uses: alex-page/blazing-fast-gh-pages-deploy@master
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: "build/"
         
